server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/market?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Market System Api
  github: https://github.com/MurilloMarquesSantos/marketApi

