global:
  scrape_interval:     15s


#  external_labels:
#    monitor: 'codelab-monitor'


scrape_configs:

  - job_name: 'Market-Actuator'


    scrape_interval: 5s

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets: ['host.docker.internal:8080']